[[plugins]]
repo = 'Shougo/neomru.vim'
on_path = '.*'

[[plugins]]
repo = 'Shougo/unite.vim'
depends = 'neomru.vim'
on_cmd = ['Unite', 'UniteWithBufferDir', 'UniteWithCurrentDir']

[[plugins]]
repo = 'aklt/plantuml-syntax'
on_ft = ['plantuml']

[[plugins]]
repo = 'nathanaelkane/vim-indent-guides'
on_ft = ['yaml']

[[plugins]]
repo = 'basyura/unite-rails'
depends = 'unite.vim'
on_ft = ['rb', 'ruby', 'erb']

[[plugins]]
repo = 'mustache/vim-mustache-handlebars'
on_ft = ['mustache']

[[plugin]]
repo = 'OrangeT/vim-csharp'
on_ft = ['cs', 'csi', 'csx']

[[plugin]]
repo = 'vim-ruby/vim-ruby'
on_ft = ['ruby', 'rb', 'erb']

[[plugin]]
repo = 'tpope/vim-bundler'
on_ft = ['ruby', 'rb', 'erb']

[[plugin]]
repo = 'tpope/gem-ctags'
on_ft = ['ruby', 'rb', 'erb']

[[plugins]]
repo = 'tpope/vim-rails'
on_ft = ['ruby', 'rb', 'erb']

[[plugins]]
repo = 'yuku-t/vim-ref-ri'
on_ft = ['ruby', 'rb', 'erb']

[[plugins]]
repo = 'mhinz/vim-mix-format'
on_ft = ['ex', 'exs', 'eex', 'leex']

[[plugins]]
repo = 'sebdah/vim-delve'
on_ft = ['go']
