[[plugins]]
repo = 'Shougo/neomru.vim'
on_path = '.*'

# [[plugins]]
# repo = 'Shougo/neocomplcache'
# if = '!has("lua")'
# on_i = 1
# 
# [[plugins]]
# repo = 'Shougo/neocomplete'
# if = 'has("lua")'
# on_i = 1

[[plugins]]
repo = 'Shougo/unite.vim'
depends = 'neomru.vim'
on_cmd = ['Unite', 'UniteWithBufferDir', 'UniteWithCurrentDir']

[[plugins]]
repo = 'aklt/plantuml-syntax'
on_ft = ['plantuml']

[[plugins]]
repo = 'nathanaelkane/vim-indent-guides'
on_ft = ['yaml']

[[plugins]]
repo = 'basyura/unite-rails'
depends = 'unite.vim'
on_ft = ['rb', 'ruby', 'erb']

[[plugins]]
repo = 'iyuuya/unite-rails-fat'
depends = 'unite.vim'
on_ft = ['rb', 'ruby', 'erb']

[[plugins]]
repo = 'mustache/vim-mustache-handlebars'
on_ft = ['mustache']

[[plugin]]
repo = 'OrangeT/vim-csharp'
on_ft = ['cs', 'csi', 'csx']

[[plugins]]
repo = 'OmniSharp/omnisharp-vim'
on_ft = ['cs', 'csi', 'csx']
build = 'xbuild server/OmniSharp.sln'

[[plugin]]
repo = 'vim-ruby/vim-ruby'
on_ft = ['ruby', 'rb', 'erb']

[[plugin]]
repo = 'tpope/vim-bundler'
on_ft = ['ruby', 'rb', 'erb']

[[plugin]]
repo = 'tpope/gem-ctags'
on_ft = ['ruby', 'rb', 'erb']

[[plugins]]
repo = 'tpope/vim-rails'
on_ft = ['ruby', 'rb', 'erb']

[[plugins]]
repo = 'yuku-t/vim-ref-ri'
on_ft = ['ruby', 'rb', 'erb']

[[plugins]]
repo = 'fatih/vim-go'
on_ft = 'go'
hook_add = '''
  " 保存時に必要なimportを自動的に挿入
  let g:go_fmt_command = "goimports"
  " LSPに任せる機能をOFFにする
  let g:go_def_mapping_enabled = 0
  let g:go_doc_keywordprg_enabled = 0
'''

[[plugins]]
repo = 'zchee/deoplete-go'
on_ft = 'go'
build = 'make'

[[plugins]]
repo = 'mhinz/vim-mix-format'
on_ft = ['ex', 'exs', 'eex', 'leex']
