[[plugins]]
repo = 'Shougo/dein.vim'

[[plugins]]
repo = 'Shougo/vimproc.vim'
build = 'make'

[[plugins]]
repo = 'vim-scripts/L9'

[[plugins]]
repo = 'kassio/neoterm'
if = 'has("nvim")'

[[plugins]]
repo = 'editorconfig/editorconfig-vim'

[[plugins]]
repo = 'Shougo/vimfiler'

[[plugins]]
depends = 'kana/vim-smartinput'
repo = 'cohama/vim-smartinput-endwise'

[[plugins]]
repo = 'kana/vim-smartinput'

[[plugins]]
repo = 'rhysd/clever-f.vim'

[[plugins]]
repo = 'tomtom/tcomment_vim'

[[plugins]]
repo = 'rking/ag.vim'

[[plugins]]
repo = 'tpope/vim-fugitive'

[[plugins]]
repo = 'airblade/vim-gitgutter'

[[plugins]]
repo = 'cohama/agit.vim'

[[plugins]]
repo = 'alpacatc/alpaca_tags'
depends = 'Shougo/vimproc'
on_cmd = ['AlpacaTagsUpdate', 'AlpacaTagsSet', 'AlpacaTagsBundle']

[[plugins]]
repo = 'junegunn/fzf'

[[plugins]]
repo = 'osyo-manga/vim-precious'
depends = ['context_filetype.vim']

[[plugins]]
repo = 'Shougo/context_filetype.vim'

[[plugins]]
repo = 'Shougo/denite.nvim'

[[plugins]]
repo = 'Shougo/deoplete.nvim'
on_i = 1
hook_source = '''
  let g:deoplete#enable_at_startup = 1
'''

[[plugins]]
repo = 'fishbullet/deoplete-ruby'
on_ft = ['rb', 'ruby', 'erb']
on_i = 1

##########################
## colorscheme
##########################

# [[plugins]]
# repo = 'altercation/vim-colors-solarized'

[[plugins]]
repo = 'frankier/neovim-colors-solarized-truecolor-only'
build = "cp ~/.cache/dein/repos/github.com/frankier/neovim-colors-solarized-truecolor-only/colors/*.vim ~/.vim/colors/"

[[plugins]]
repo = 'nanotech/jellybeans.vim'
build = "cp ~/.cache/dein/repos/github.com/nanotech/jellybeans/colors/*.vim ~/.vim/colors/"

[[plugins]]
repo = 'tomasr/molokai'
build = "cp ~/.cache/dein/repos/github.com/tomasr/molokai/colors/*.vim ~/.vim/colors/"

[[plugins]]
repo = 'baskerville/bubblegum'
build = "cp ~/.cache/dein/repos/github.com/baskerville/bubblegum/colors/*.vim ~/.vim/colors/"

[[plugins]]
repo = 'w0ng/vim-hybrid'
build = "cp ~/.cache/dein/repos/github.com/w0ng/vim-hybrid/colors/*.vim ~/.vim/colors/"

[[plugins]]
repo = 'vim-scripts/twilight'
build = "cp ~/.cache/dein/repos/github.com/vim-scripts/twilight/colors/*.vim ~/.vim/colors/"

[[plugins]]
repo = 'jonathanfilip/vim-lucius'
build = "cp ~/.cache/dein/repos/github.com/jonathanfilip/vim-lucius/colors/*.vim ~/.vim/colors/"

[[plugins]]
repo = 'jpo/vim-railscasts-theme'
build = "cp ~/.cache/dein/repos/github.com/jpo/vim-railscasts-theme/colors/*.vim ~/.vim/colors/"

[[plugins]]
repo = 'carakan/new-railscasts-theme'
build = "cp ~/.cache/dein/repos/github.com/carakan/new-railscasts-theme/colors/*.vim ~/.vim/colors/"

[[plugins]]
repo = 'chriskempson/vim-tomorrow-theme'
build = "cp ~/.cache/dein/repos/github.com/chriskempson/vim-tomorrow-theme/colors/*.vim ~/.vim/colors/"

[[plugins]]
repo = 'ujihisa/unite-colorscheme'

[[plugins]]
repo = 'scrooloose/syntastic'

[[plugins]]
repo = 'thinca/vim-ref'

[[plugins]]
repo = 'neomake/neomake'
hook_add = '''
let g:neomake_open_list = 2
autocmd! BufWritePost * Neomake
'''
