cask_args appdir: '/Applications'

tap "aylei/tap"
tap "golangci/tap"
tap "homebrew/bundle"
tap "homebrew/cask"
tap "homebrew/cask-versions"
tap "homebrew/core"
tap "homebrew/services"
tap "ktr0731/evans"
tap "neovim/neovim"
tap "sanemat/font"

brew "sqlite"
brew "autoconf"
brew "automake"
brew "bash-completion"
brew "colordiff"
brew "coreutils"
brew "ctags"
brew "curl"
brew "diffutils"
brew "direnv"
brew "findutils"
brew "libtool"
brew "gawk"
brew "gcc"
brew "ghq"
brew "git"
brew "gnu-getopt"
brew "gnu-sed"
brew "gnu-tar"
brew "go"
brew "graphviz"
brew "grep"
brew "gzip"
brew "helm"
brew "hub"
brew "oniguruma"
brew "jq"
brew "kubernetes-cli"
brew "kube-ps1"
brew "kubectx"
brew "kustomize"
brew "less"
brew "libevent"
brew "libsass"
brew "lua"
brew "lv"
brew "make"
brew "mas"
brew "maven"
brew "msgpack"
brew "mysql"
brew "ncurses"
brew "neovim"
brew "nodebrew"
brew "openssh"
brew "openssl@1.1"
brew "peco"
brew "postgresql"
brew "protobuf"
brew "pwgen"
brew "pyenv"
brew "pyenv-virtualenv"
brew "ruby-build"
brew "rbenv"
brew "rbenv-default-gems"
brew "redis"
brew "rsync"
brew "ruby"
brew "shellcheck"
brew "shtool"
brew "ssh-copy-id"
brew "stern"
brew "the_silver_searcher"
brew "tig"
brew "tmux"
brew "vim"
brew "watch"
brew "watchman"
brew "wget"
brew "yarn"
brew "zsh"
brew "zsh-completions"
brew "aylei/tap/kubectl-debug"
brew "golangci/tap/golangci-lint"
brew "sanemat/font/ricty"
brew "zlib"
# cask "alfred"
# cask "docker"
# cask "google-cloud-sdk"
# cask "google-japanese-ime"
# cask "hyperswitch"
# cask "iterm2"
# cask "kindle"
# cask "licecap"
# cask "skitch"
# cask "skype"
# cask "slack"
# cask "visual-studio-code"

mas "1Password 7", id: 1333542190
mas "BetterSnapTool", id: 417375580
